### ISSUE TITLE
What is the spec for a valid prefix / suffix etc?

### ISSUE THREAD

**Issue by uskay** [uskay/scroll-to-fragment-for-search-demo#1]
It seems the browser is matching based on word (morphology?) basis, so it's not the same as cmd+f browser search, but where is the spec for this? i.e. English are rather easy b/c it has limited delimiters between the words e.g. space. What about Japanese and other languages?

### English
Works: [#:~:text=the-,performance%20and%20interactivity%20of%20the%20system,-weren't](https://en.wikipedia.org/wiki/Google_Chrome#:~:text=the-,performance%20and%20interactivity%20of%20the%20system,-weren't)
Doesn't work: [#:~:text=the-,performance%20and%20interactivity%20of%20the%20system,-were](https://en.wikipedia.org/wiki/Google_Chrome#:~:text=the-,performance%20and%20interactivity%20of%20the%20system,-were)
Also, this doesn't work (no prefix/suffix. Only textStart. Intentionally removing the last 'm' from the word 'system'.): [performance%20and%20interactivity%20of%20the%20syste](https://en.wikipedia.org/wiki/Google_Chrome#:~:text=performance%20and%20interactivity%20of%20the%20syste)

### Japanese
Works: [#:~:text=テレビ東京系の番組『-,ドリームクリエイター,-』に出演したことを](https://ja.wikipedia.org/wiki/%E8%97%A4%E6%A3%AE%E6%85%8E%E5%90%BE#:~:text=%E3%83%86%E3%83%AC%E3%83%93%E6%9D%B1%E4%BA%AC%E7%B3%BB%E3%81%AE%E7%95%AA%E7%B5%84%E3%80%8E-,%E3%83%89%E3%83%AA%E3%83%BC%E3%83%A0%E3%82%AF%E3%83%AA%E3%82%A8%E3%82%A4%E3%82%BF%E3%83%BC,-%E3%80%8F%E3%81%AB%E5%87%BA%E6%BC%94%E3%81%97%E3%81%9F%E3%81%93%E3%81%A8%E3%82%92)
Doesn't work: [#:~:text=テレビ東京系の番組『-,ドリームクリエイター,-』に出演したことをき](https://ja.wikipedia.org/wiki/%E8%97%A4%E6%A3%AE%E6%85%8E%E5%90%BE#:~:text=%E3%83%86%E3%83%AC%E3%83%93%E6%9D%B1%E4%BA%AC%E7%B3%BB%E3%81%AE%E7%95%AA%E7%B5%84%E3%80%8E-,%E3%83%89%E3%83%AA%E3%83%BC%E3%83%A0%E3%82%AF%E3%83%AA%E3%82%A8%E3%82%A4%E3%82%BF%E3%83%BC,-%E3%80%8F%E3%81%AB%E5%87%BA%E6%BC%94%E3%81%97%E3%81%9F%E3%81%93%E3%81%A8%E3%82%92%E3%81%8D)

**Comment by uskay** [comment]
@KenjiBaheux, @tomayac do you know?

**Comment by tomayac** [comment]
> Also, this doesn't work (no prefix/suffix. Only textStart): [performance%20and%20interactivity%20of%20the%20syste](https://en.wikipedia.org/wiki/Google_Chrome#:~:text=performance%20and%20interactivity%20of%20the%20syste)

This is purely a typo (lacks the last 'm'). The [fixed link](https://en.wikipedia.org/wiki/Google_Chrome#:~:text=performance%20and%20interactivity%20of%20the%20system) works.

Doing more research for the other questions.

**Comment by tomayac** [comment]
The spec has the [following](https://wicg.github.io/scroll-to-text-fragment/#word-boundaries) to say: matches are limited to word boundaries. Limiting matching to word boundaries is one of the mitigations to limit cross-origin information leakage. In Japanese there is no character that separates one word from the next. In such cases, and where the alphabet contains fewer than 100 characters, the dictionary must not contain more than 20% of the alphabet as valid, one-letter words. The used word boundaries are defined [here](https://www.unicode.org/reports/tr29/tr29-37.html#Default_Word_Boundaries) (and specifically [here](https://www.unicode.org/reports/tr29/tr29-37.html#Katakana) for Katakana). In the Japanese string "ウィキペディアへようこそ" (Welcome to Wikipedia), "ようこそ" (Welcome) is considered word-bounded but "ようこ" is not. I don't speak Japanese, but does this make sense in the given context?

**Comment by uskay** [comment]
> This is purely a typo (lacks the last 'm'). 

Thanks Tom, actually that was intended (testing to see what happens when removing the 'm'). I'm trying to understand the spec here and how and why those cases would/wouldn't work.

> Limiting matching to word boundaries

Thank you, this is super helpful! This is the exact explanation I needed and will be looking at how best to accommodate this restriction for Japanese... feeling I would be needing some kind of a library like https://github.com/takuyaa/kuromoji.js to do this.

**Comment by uskay** [comment]
Fixed https://github.com/uskay/scroll-to-fragment-for-search-demo/commit/b27097b984e7c3603c71285817db59fd00153a3f
